version: '3.9'

services:
  api:
    restart: always
    build: 
      context: .
    environment:
      - APPLICATION_TYPE=REST
    ports:
      - 8000:8000
    volumes:
      - ./:/project
    entrypoint: ['uvicorn', 'src.main:entrypoint', '--reload', '--host', '0.0.0.0']

  broker:
    restart: always
    image: nats:2.8-alpine
    ports:
      - 4222:4222
      - 8222:8222

  messaging:
    restart: always
    build: 
      context: .
    depends_on:
      - broker
    environment:
      - APPLICATION_TYPE=MESSAGING
    ports:
      - 8001:8001
    volumes:
      - ./:/project
    entrypoint: ['python3', '-m', 'src.main']